# Generated by Django 4.2.1 on 2023-06-04 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yarn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('colour', models.ManyToManyField(to='gallery.colour')),
                ('yarn_manufacturer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gallery.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='Sweater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to=None)),
                ('needles', models.ManyToManyField(to='gallery.needles')),
                ('yarn', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gallery.yarn')),
            ],
        ),
    ]
