# Generated by Django 4.2.1 on 2023-06-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_rename_yarn_manufacturer_yarn_manufacturer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sweater',
            name='colour',
            field=models.ManyToManyField(to='gallery.colour'),
        ),
    ]
