# Generated by Django 4.2.1 on 2023-06-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_sweater_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sweater',
            name='colour',
            field=models.ManyToManyField(limit_choices_to={'yarn__iexact=yarn': True}, to='gallery.colour'),
        ),
    ]
