# Generated by Django 4.2.1 on 2023-06-05 10:13

from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_alter_sweater_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sweater',
            name='colour',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='yarn', chained_model_field='yarn', horizontal=True, to='gallery.colour', verbose_name='colour'),
        ),
    ]
