# Generated by Django 4.2.1 on 2023-06-05 10:19

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_alter_sweater_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='colour',
            name='manufacturer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gallery.manufacturer'),
        ),
        migrations.AlterField(
            model_name='colour',
            name='yarn',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='manufacturer', chained_model_field='manufacturer', on_delete=django.db.models.deletion.CASCADE, to='gallery.yarn'),
        ),
    ]
