# Generated by Django 4.2.1 on 2023-06-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_colour_manufacturer_alter_colour_yarn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colour',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='sweater',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
